---
# tasks file for app-sbgrid-server

- name: Make a service account for sbgrid
  user:
    name: sbgrid
    home: /var/lib/sbgrid
    shell: /sbin/nologin
  tags:
    - sbgrid_server_crononly
    - sbgrid_server_fullinstall

- name: Ensure that the install directory is present and owned by sbgrid
  file:
    path: "{{ sb_install_target }}"
    state: directory
    mode: "0775"
    owner: sbgrid
    recurse: yes
  tags:
    - sbgrid_server_crononly
    - sbgrid_server_fullinstall

- name: Fetch the most current SBGrid install script
  get_url:
    url: "http://sync.sbgrid.org/downloads/{{ sb_sitename }}/sbgrid-admin"
    dest: /var/lib/sbgrid/sbgrid-admin
    mode: "0550"
  register: sbgrid_script_web
  ignore_errors: yes
  become: yes
  become_user: sbgrid
  tags:
    - sbgrid_server_crononly
    - sbgrid_server_fullinstall

- name: Use the SBGrid install script in this role as a fallback if the web one doesn't work
  copy:
    src: sbgrid-admin
    dest: /var/lib/sbgrid/sbgrid-admin
    mode: "0550"
  when: sbgrid_script_web.msg != 200
  become: yes
  become_user: sbgrid
  tags:
    - sbgrid_server_crononly
    - sbgrid_server_fullinstall

- name: Install the SBGrid config file
  template:
    src: sbgridrc.j2
    dest: /var/lib/sbgrid/.sbgridrc
    mode: "0440"
    owner: sbgrid
  tags:
    - sbgrid_server_crononly
    - sbgrid_server_fullinstall

# The cronjob will be overwritten by the sbgrid-admin script
# the first time it is invoked.
# This will only execute if the tag is explicitly requested (see https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags)
- name: Add cronjob if it does not exist already.
  cron:
    name: "SBGrid update cronjob"
    minute: "*/15"
    job: "/var/lib/sbgrid/sbgrid-admin -c"
    user: sbgrid
  tags:
    - never
    - sbgrid_server_crononly

# Timeout for expect module needs to be null for async to work properly.
# This will only execute if the tag is explicitly requested (see https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags)
- name: Run the install script asynchronously.  Assume downloads take 2 days max.
  expect:
    command: /bin/bash -c "/var/lib/sbgrid-admin -i"
    timeout: null
    responses:
      Would you like to change these settings *: "n"
      Shall we proceed? *: "y"
  async: 172800
  poll: 0
  become: yes
  become_user: sbgrid
  tags:
    - never
    - sbgrid_server_fullinstall
